$primary = rgb(67b3e4)
$surface = rgb(192024)
$secondary = rgb(5c67d6)
$error = rgb(fd4663)
$tertiary = rgb(cc8566)
$surface_lowest = rgb(0d1012)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
