color0 #192024
color1 #fd4663
color2 #67b3e4
color3 #5c67d6
color4 #cc8566
color5 #93c9ec
color6 #969de9
color7 #f2f2f3
color8 #5e6b73
color9 #fd4663
color10 #67b3e4
color11 #5c67d6
color12 #cc8566
color13 #93c9ec
color14 #969de9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #192024
background            #192024
foreground            #f2f2f3
selection_foreground  #afb3b6
selection_background  #222a30
active_border_color   #67b3e4
inactive_border_color #222a30
url_color             #67b3e4

active_tab_foreground   #182025
active_tab_background   #67b3e4
inactive_tab_foreground #afb3b6
inactive_tab_background #222a30
cursor_trail_color      #afb3b6
