general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
    no_fade_in = true
}

# Монолитный черный фон
background {
    monitor =
    color = rgb(0, 0, 0)
}

# Контрастное табло времени (часы, минуты, секунды)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    color = rgb(255, 255, 255)
    font_size = 110
    font_family = JetBrains Mono Bold
    position = 0, 40
    halign = center
    valign = center
}

# Дата и день недели под часами
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A · %d %B %Y" | tr '[:lower:]' '[:upper:]')"
    color = rgb(138, 138, 138)
    font_size = 14
    font_family = JetBrains Mono
    position = 0, -50
    halign = center
    valign = center
}

# Невидимое поле ввода (слепой ввод пароля без индикаторов)
input-field {
    monitor =
    size = 0, 0
    outline_thickness = 0
    dots_size = 0.0
    dots_spacing = 0.0
    fade_on_empty = false
    font_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    outer_color = rgba(0, 0, 0, 0)
    check_color = rgba(0, 0, 0, 0)
    fail_color = rgba(0, 0, 0, 0)
    placeholder_text = ""
    fail_text = ""
    position = 0, -2000
    halign = center
    valign = center
}
