general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = niri msg action power-on-monitors
}

# 1. Спустя 5 минут (300 сек): блокировка экрана hyprlock
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 2. Спустя 10 минут (600 сек): полное выключение экранов
listener {
    timeout = 600
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}
